### ISSUE TITLE
Run OAF validator on goaf

### ISSUE THREAD

**Issue by arbakker** [PDOK/goaf#28]
See [OGC validator](https://cite.opengeospatial.org/teamengine/)

**Comment by WouterVisscher** [comment]
It seems the bboxc test is done against a bbox spec:
```yaml
schema:
  type: array
  minItems: 4
  maxItems: 4
```
instead of:

```yaml
schema:
  type: array
  oneOf:
  - minItems: 4
    maxItems: 4
  - minItems: 6
    maxItems: 6
```
probably need to make a issue on ->https://github.com/opengeospatial/ets-ogcapi-features10/issues

![image](https://user-images.githubusercontent.com/15999389/123510285-cedee380-d67a-11eb-965f-ba44b8138efb.png)
